spring:
  application:
    name: product-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/wintershop}
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}

server:
  port: 8001

jwt:
  auth:
    converter:
      resource-id: alibou-rest-api
      principle-attribute: preferred_username
